name: Update Pronote timetable

on:
  schedule:
    - cron: '0 */2 * * *'   # toutes les 2 heures
  workflow_dispatch:        # permet de lancer manuellement depuis l'onglet Actions

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run fetch script
        env:
          PRONOTE_URL: ${{ secrets.PRONOTE_URL }}
          PRONOTE_USERNAME: ${{ secrets.PRONOTE_USERNAME }}
          PRONOTE_PASSWORD: ${{ secrets.PRONOTE_PASSWORD }}
        run: python fetch_pronote.py

      - name: Commit emploi.csv if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add emploi.csv || true
          if ! git diff --cached --quiet; then
            git commit -m "Update emploi.csv (automatique)"
            git push
          else
            echo "No changes to commit."
          fi
